[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
authors = [
	{ name = "David Navarro-Payá", email = "david.navarro.paya@gmail.com" },
	{ name = "Antonio Santiago", email = "antsanpaj@gmail.com" },
	{ name = "Amandine Velt", email = "Amandine.Velt@inrae.fr" },
]
name = "aegis-bio"
version = "0.3.16"
description = "Annotation Extraction Genomic Integration Suite."
readme = "README.md"
requires-python = ">=3.12.3"
classifiers = [
	"Programming Language :: Python :: 3",
	"Operating System :: OS Independent"
]

license = "GPL-3.0-or-later"
license-files = ["LICENSE.md"]

dependencies = [
    "biopython>=1.81",
    "colorlover>=0.3.0",
    "matplotlib>=3.5.3",
    "networkx>=2.6.3",
    "pandas>=1.1.5",
    "plotly>=5.18.0",
    "scipy>=1.7.3",
    "tqdm>=4.67.1",
    "typer>=0.16.1",
    "typing_extensions>=4.15.0",
    "pytest>=8.4.1",
    "kaleido>=0.2.1"
]

[tool.setuptools]
packages = ["aegis", "aegis.cli", "aegis.utils", "aegis.annotation_components"]

[project.scripts]
aegis = "aegis.cli:app"

[project.urls]
"Homepage" = "https://github.com/tomsbiolab/aegis"
"Bug Tracker" = "https://github.com/tomsbiolab/aegis/issues"
"Documentation" = "https://github.com/tomsbiolab/aegis#readme"
"Source Code" = "https://github.com/tomsbiolab/aegis"
"Docker Hub" = "https://hub.docker.com/r/tomsbiolab/aegis"